/*
 * ActorEditor.java
 *
 * Created on 26 de Novembro de 2008, 18:49
 */

package org.gcreator.editors;

import javax.swing.JPanel;
import org.gcreator.game2d.PaletteUser;
import org.gcreator.gui.DocumentPane;
import org.gcreator.project.io.BasicFile;
import org.noos.xing.mydoggy.ToolWindow;

/**
 *
 * @author  luis
 */
public class ActorEditor extends DocumentPane implements PaletteUser{
    
    private static final long serialVersionUID = 1L;

    /**
     * Creates a new ActorEditor
     * @param f The actor file
     */
    public ActorEditor(BasicFile f) {
        super(f);
        initComponents();
    }
    
    public boolean doPalette(ToolWindow window, JPanel palette){
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
